{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "cluster-octopus.namespace" . }}
  labels:
    {{- include "cluster-octopus.labels" . | nindent 4 }}
{{- end }}
